spring:
  devtools:
    restart:
      enabled: true

logging:
  level:
    com.nt.sns: DEBUG
    org.springframework.security: DEBUG
    org.mybatis: DEBUG

springdoc:
  swagger-ui:
    enabled: true
