spring:
  devtools:
    restart:
      enabled: true

logging:
  level:
    com.nt.sns: ${LOG_LEVEL_APP:DEBUG}
    org.springframework.security: ${LOG_LEVEL_SECURITY:DEBUG}
    org.mybatis: ${LOG_LEVEL_MYBATIS:DEBUG}

springdoc:
  swagger-ui:
    enabled: true
